### ISSUE TITLE
Couldn't load <div class="form-group"....> to create another table data in form

### ISSUE THREAD

**Issue by RGTimothy** [mootensai/yii2-enhanced-gii#44]
There is an error when the form file was loading another view (which will be shown on the bottom of the current form as usual).

![4](https://cloud.githubusercontent.com/assets/3026828/13274999/b5ff163a-dae2-11e5-9211-2decf59dd1fb.PNG)

![5](https://cloud.githubusercontent.com/assets/3026828/13275003/c0ed93f0-dae2-11e5-8c93-dbc5bef722e6.PNG)
![3](https://cloud.githubusercontent.com/assets/3026828/13275005/c453cb40-dae2-11e5-965a-7a8bb557b002.PNG)

**Comment by mootensai** [comment]
please right click & "open response on new tab" on the error at firebug

**Comment by RGTimothy** [comment]
Do you mean that I have to type "yii init" and choose dev mode? I think it will be not recognized since I'm using basic template yii now. Do you have any solution for this? Thanks.

**Comment by mootensai** [comment]
please right click & "open response on new tab" on the error at firebug

**Comment by RGTimothy** [comment]
I have included that screenshoot on my 1st comment above. As you can see, I attached 3 images, and what you mentioned is on the 3rd images.

**Comment by mootensai** [comment]
I need the full response of what's on the console that's outputting the error log on the first image

**Comment by RGTimothy** [comment]
Do you mean this error log?

```
<pre>PHP Recoverable Error &#039;yii\base\ErrorException&#039; with message &#039;Object of class Closure
 could not be converted to string&#039; 

in C:\wamp\www\sysnet\vendor\yiisoft\yii2\helpers\BaseHtml.php:144

Stack trace:
#0 C:\wamp\www\sysnet\vendor\yiisoft\yii2\helpers\BaseHtml.php(144): yii\base\ErrorHandler-&gt;handleError
(4096, &#039;Object of class...&#039;, &#039;C:\\wamp\\www\\sys...&#039;, 144, Array)
#1 C:\wamp\www\sysnet\vendor\kartik-v\yii2-builder\TabularForm.php(176): yii\helpers\BaseHtml::tag(&
#039;div&#039;, Object(Closure), Array)
#2 [internal function]: kartik\builder\TabularForm-&gt;kartik\builder\{closure}(Array, 0, 0, Object(kartik
\grid\DataColumn))
#3 C:\wamp\www\sysnet\vendor\yiisoft\yii2\grid\DataColumn.php(190): call_user_func(Object(Closure), Array
, 0, 0, Object(kartik\grid\DataColumn))
#4 C:\wamp\www\sysnet\vendor\yiisoft\yii2\grid\DataColumn.php(204): yii\grid\DataColumn-&gt;getDataCellValue
(Array, 0, 0)
#5 C:\wamp\www\sysnet\vendor\kartik-v\yii2-grid\DataColumn.php(332): yii\grid\DataColumn-&gt;renderDataCellContent
(Array, 0, 0)
#6 C:\wamp\www\sysnet\vendor\yiisoft\yii2\grid\GridView.php(504): kartik\grid\DataColumn-&gt;renderDataCell
(Array, 0, 0)
#7 C:\wamp\www\sysnet\vendor\yiisoft\yii2\grid\GridView.php(473): yii\grid\GridView-&gt;renderTableRow
(Array, 0, 0)
#8 C:\wamp\www\sysnet\vendor\kartik-v\yii2-grid\GridView.php(797): yii\grid\GridView-&gt;renderTableBody
()
#9 C:\wamp\www\sysnet\vendor\yiisoft\yii2\grid\GridView.php(344): kartik\grid\GridView-&gt;renderTableBody
()
#10 C:\wamp\www\sysnet\vendor\yiisoft\yii2\widgets\BaseListView.php(151): yii\grid\GridView-&gt;renderItems
()
#11 C:\wamp\www\sysnet\vendor\yiisoft\yii2\grid\GridView.php(313): yii\widgets\BaseListView-&gt;renderSection
(&#039;{items}&#039;)
#12 C:\wamp\www\sysnet\vendor\yiisoft\yii2\widgets\BaseListView.php(126): yii\grid\GridView-&gt;renderSection
(&#039;{items}&#039;)
#13 [internal function]: yii\widgets\BaseListView-&gt;yii\widgets\{closure}(Array)
#14 C:\wamp\www\sysnet\vendor\yiisoft\yii2\widgets\BaseListView.php(129): preg_replace_callback(&#039
;/{\\w+}/&#039;, Object(Closure), &#039;&lt;div class=&quot;pan...&#039;)
#15 C:\wamp\www\sysnet\vendor\yiisoft\yii2\grid\GridView.php(288): yii\widgets\BaseListView-&gt;run(
)
#16 C:\wamp\www\sysnet\vendor\kartik-v\yii2-grid\GridView.php(767): yii\grid\GridView-&gt;run()
#17 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\Widget.php(98): kartik\grid\GridView-&gt;run()
#18 C:\wamp\www\sysnet\vendor\kartik-v\yii2-builder\TabularForm.php(281): yii\base\Widget::widget(Array
)
#19 C:\wamp\www\sysnet\vendor\kartik-v\yii2-builder\TabularForm.php(116): kartik\builder\TabularForm-
&gt;renderGrid()
#20 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\Widget.php(98): kartik\builder\TabularForm-&gt;run()

#21 C:\wamp\www\sysnet\views\sales-key-focus-plan\_formSalesKeyFocusPlanDetail.php(61): yii\base\Widget
::widget(Array)
#22 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\View.php(325): require(&#039;C:\\wamp\\www\\sys...&#039
;)
#23 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\View.php(247): yii\base\View-&gt;renderPhpFile(&#039
;C:\\wamp\\www\\sys...&#039;, Array)
#24 C:\wamp\www\sysnet\vendor\yiisoft\yii2\web\View.php(210): yii\base\View-&gt;renderFile(&#039;C:\
\wamp\\www\\sys...&#039;, Array, Object(app\controllers\SalesKeyFocusPlanController))
#25 C:\wamp\www\sysnet\vendor\yiisoft\yii2\web\Controller.php(47): yii\web\View-&gt;renderAjax(&#039
;_formSalesKeyFo...&#039;, Array, Object(app\controllers\SalesKeyFocusPlanController))
#26 C:\wamp\www\sysnet\controllers\SalesKeyFocusPlanController.php(177): yii\web\Controller-&gt;renderAjax
(&#039;_formSalesKeyFo...&#039;, Array)
#27 [internal function]: app\controllers\SalesKeyFocusPlanController-&gt;actionAddSalesKeyFocusPlanDetail
()
#28 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array
)
#29 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction-&gt;runWithParams
(Array)
#30 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller-&gt;runAction(&
#039;add-sales-key-f...&#039;, Array)
#31 C:\wamp\www\sysnet\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module-&gt;runAction(&#039
;sales-key-focus...&#039;, Array)
#32 C:\wamp\www\sysnet\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application-&gt;handleRequest
(Object(yii\web\Request))
#33 C:\wamp\www\sysnet\web\index.php(12): yii\base\Application-&gt;run()
#34 {main}</pre>
```

**Comment by mootensai** [comment]
what's on `_formSalesKeyFocusPlanDetail.php` 
line 61?

**Comment by RGTimothy** [comment]
![c1](https://cloud.githubusercontent.com/assets/3026828/13275250/6e8a6da6-dae5-11e5-9f11-f16b3f29ffd5.PNG)

**Comment by mootensai** [comment]
looks like i'm gonna need the whole file :sweat:

**Comment by RGTimothy** [comment]
Here I attached the file.
[_formSalesKeyFocusPlanDetail.zip](https://github.com/mootensai/yii2-enhanced-gii/files/143911/_formSalesKeyFocusPlanDetail.zip)

**Comment by mootensai** [comment]
can you show me your PHP info? what's the PHP version you're using?

**Comment by RGTimothy** [comment]
my PHP Version is 5.5.12

Is the error related to my development platform?

**Comment by mootensai** [comment]
I'm not really sure about that, but I can't reproduce the error. 
I use 
PHP Version 5.6.14

could you help me find which Closure that produce this error?

**Comment by RGTimothy** [comment]
I think the problem is these lines of code. Please check this out. When I comment all of these lines, there is no error found.

![err1](https://cloud.githubusercontent.com/assets/3026828/13276029/afa2d672-daed-11e5-9517-a10f3371972c.PNG)

**Comment by RGTimothy** [comment]
The issue is on this line :
`'type' => TabularForm::INPUT_STATIC,` 

It will be solved if I changed it into:
`'type' => 'raw',`

Dont know why. Do you have any solution for this? Thanks.

**Comment by mootensai** [comment]
Wow! Thanks! I don't know what to do to fix that code..
:smile:

**Comment by mootensai** [comment]
I don't know what cause the error. I never got that error and I can't reproduce that error.

Maybe I should change the generator to generate 
`'type' => 'raw'` 
instead of 
`'type' => TabularForm::INPUT_STATIC`

**Comment by mootensai** [comment]
Thanks!

**Comment by RGTimothy** [comment]
You're welcome.
